% created Feb 12, 2019
% updated last: Feb 24, 2019
% read data code generated by MATLAB import tool, so don't ask me how to do
% it

%%%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/nhiasolari/Desktop/MATLAB/GEOS 350/Core Densities.xlsx
%    Worksheet: Wet density (F18)
%
% Auto-generated by MATLAB on 16-Feb-2019 19:54:31

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = "Wet density (F18)";
opts.DataRange = "A3:D31";

% Specify column names and types
opts.VariableNames = ["Depth", "WAB18GC1", "WAB18GC2", "WAB18GC3"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Import the data
CoreDensitiesS1 = readtable("Core Densities.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/nhiasolari/Desktop/MATLAB/GEOS 350/Core Densities.xlsx
%    Worksheet: Dry density (F18)
%
% Auto-generated by MATLAB on 16-Feb-2019 19:56:31

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = "Dry density (F18)";
opts.DataRange = "A3:D31";

% Specify column names and types
opts.VariableNames = ["Depth", "WAB18GC1", "WAB18GC2", "WAB18GC3"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Import the data
CoreDensities = readtable("Core Densities.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/nhiasolari/Desktop/MATLAB/GEOS 350/WAB18-GC1.xlsx
%    Worksheet: Density
%
% Auto-generated by MATLAB on 16-Feb-2019 19:58:28

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 10);

% Specify sheet and range
opts.Sheet = "Density";
opts.DataRange = "A2:J24";

% Specify column names and types
opts.VariableNames = ["Depthcm", "Volumecc", "WeightofCapandTubeg", "WetWeightwtubeg", "WetWeightg", "WaterWeightg", "DryWeightwtube", "DryWeightg", "WetDensity", "DryDensity"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
WAB18GC1 = readtable("WAB18-GC1.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/nhiasolari/Desktop/MATLAB/GEOS 350/WAB18-GC3.xlsx
%    Worksheet: Density
%
% Auto-generated by MATLAB on 16-Feb-2019 19:59:14

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 10);

% Specify sheet and range
opts.Sheet = "Density";
opts.DataRange = "A2:J28";

% Specify column names and types
opts.VariableNames = ["Depthcm", "Volumecc", "WeightofCapandTubeg", "WetWeightwtubeg", "WetWeightg", "WaterWeightg", "DryWeightwtube", "DryWeightg", "WetDensitygcc", "DryDensitygcc"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
WAB18GC3 = readtable("WAB18-GC3.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts

%%
%plots combined dry density for every interval for WAB18GC3 
figure(1)
set(gcf, 'Position', [500 500 500 900])
combinedDryGC3 = zeros(54,2);
combinedDryGC3(1:2:end,1) = WAB18GC3.Depthcm;
combinedDryGC3(2:2:end,1) = CoreDensities.Depth(1:27);
combinedDryGC3(1:2:end,2) = WAB18GC3.DryDensitygcc;
combinedDryGC3(2:2:end,2) = CoreDensities.WAB18GC3(1:27);
set(gca, 'YDir','reverse')
plot(combinedDryGC3(:,2), combinedDryGC3(:,1), 'Color',[0 0.8 1] , 'Linewidth', 5)
legend('WAB18GC3 Dry Density')
title('Combined WAB18GC3 Dry Density', 'FontSize', 20)
ylabel('Depth (cm)')
xlabel('Dry Density (g/cm^3)')
xlim([0 0.5])
ylim([0 55])
set (gca,'YDir','reverse')
hold off

%%
%plots combined dry density for every interval for WAB18GC1 
figure(2)
set(gcf, 'Position', [500 500 500 900])
combinedDryGC1 = zeros(46,2);
combinedDryGC1(1:2:end,1) = WAB18GC1.Depthcm;
combinedDryGC1(2:2:end,1) = CoreDensities.Depth(1:23);
combinedDryGC1(1:2:end,2) = WAB18GC1.DryDensity;
combinedDryGC1(2:2:end,2) = CoreDensities.WAB18GC1(1:23);
plot(combinedDryGC1(:,2), combinedDryGC1(:,1), 'Color',[0 1 0.8] , 'Linewidth', 5)
legend('WAB18GC1 Dry Density')
title('Combined WAB18GC1 Dry Density', 'FontSize', 20)
ylabel('Depth (cm)')
xlabel('Dry Density (g/cm^3)')
xlim([0 0.5])
ylim([0 55])
set (gca,'YDir','reverse')

%%
%plots combined dry density for WAB18GC1 and WAB18GC3
figure(3)
set(gcf, 'Position', [500 500 500 900])
plot(combinedDryGC1(:,2), combinedDryGC1(:,1), 'Color',[0 1 0.8] , 'Linewidth', 5)
hold on
plot(combinedDryGC3(:,2), combinedDryGC3(:,1), 'Color',[0 0.8 1] , 'Linewidth', 5)
legend('WAB18GC1', 'WAB18GC3')
title('Combined Dry Density', 'FontSize', 20)
ylabel('Depth (cm)')
xlabel('Dry Density (g/cm^3)')
xlim([0 0.5])
ylim([0 55])
set (gca,'YDir','reverse')

%%
%plots odd dry density for WAB18GC1 and WAB18GC3
figure(4)

set(gcf, 'Position', [500 500 500 900])
plot(WAB18GC1.DryDensity, WAB18GC1.Depthcm, 'Color',[0 1 0.8], 'Linewidth', 5)
hold on
plot(WAB18GC3.DryDensitygcc, WAB18GC3.Depthcm, 'Color',[0 0.8 1], 'Linewidth', 5)
legend('WAB18GC1', 'WAB18GC3')
title('Odd Dry Density', 'FontSize', 20)
ylabel('Depth (cm)')
xlabel('Dry Density (g/cm^3)')
xlim([0 0.5])
ylim([0 55])
set (gca,'YDir','reverse')
